### ISSUE TITLE
AuditEntry logic

### ISSUE THREAD

**Issue by Blackdread** [idugalic/digital-restaurant#7]
Sorry to ask here, not sure there is any other place to ask this question.

First: Thanks for this great example of using axon and different implementation choices.

In my project I hesitated to use something similar to AuditEntry, and use it in all commands/events.
The solution I used is putting the user id in the metadata of the command when sent from the rest controller (using an interceptor to not have to write this logic everywhere); And adding a CorrelationDataProvider to make this data follow cmds/events produced by the initial command/event.

I had chosen this way as it did not pollute my cmd/events but it is very easy to loose this metadata information when using "thenApply" or "thenCompose" or etc. I had to use extension methods that would get the context locally then call the actual method "thenApply" or "thenCompose" with the context added from the local cached value.

I think I might revert my way to use MetaData and [correlation-data](https://docs.axoniq.io/reference-guide/operations-guide/production-considerations/monitoring-and-metrics#correlation-data); And use AuditEntry in all cmd/events.

For my projects, I have not high requirements of auditing but it is still needed in some cmd/events.
Anyway it might be used later, so enforcing the AuditEntry allows to make sure that user id (and initial time) are preserved in all cmds/events that the initial cmd/event started; whereas using metadata I find myself sometimes to fix loose of information in parts of the code...

So my main question, what would be your approach to solve issue of knowing who initialized the action and when?
Would you keep using something like AuditEntry or you have found another solution that you use in more recent projects?

Thanks for you answer.

PS: Why used entities in REST? Don't you have issues with JPA lazy initialization (not all your entities are EAGER) and recursive serialization ? (I never returns entities but a DTO)

**Comment by idugalic** [comment]
Hi,

This project is demonstrating different design options with Axon by using `different` infrastructural components. 

Personally, I like to keep `identity` as part of the message payload (command, event, query). In that case, it is formally the part of the API. Additionally, (dispatch) interceptors could be used to automate the process of populating the `identity` (AuditEntry), from the Spring context for example. Sometimes, you want to use this `identity` to do some business validation or authorization on the `aggregate` level. I would keep AuditEntry :)

Regarding the DTO. I agree, having DTOs would be a better design. I believe that some modules are using Spring Data Rest, and it was faster for me to expose entities directly... These days I'm using Axon queries, and I do not expose entities there.
